
services:
  nodeseek_deepflood_signin:
    image: ghcr.io/assast/nodeseek_deepflood_signin:latest
    container_name: nodeseek_deepflood_signin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # 时区设置
      - TZ=Asia/Shanghai

